import * as gb from '../src/generator';
import * as bg from '../src/buildersGenrator';
import * as tsa from '../src/tsAnalyzer';
import * as log from '../src/logger';
import * as ts from 'typescript';
import * as fs from "fs";
import * as pathPlatformDependent from 'path';
const path = pathPlatformDependent.posix;

describe('buildersGenrator', () => {
    let testCase: { do: () => Promise<string> };
    let logger = log.create(false, false, false, false);

    describe('auto-generated header', () => {
        beforeEach(() => {
            testCase = {
                do: () => new Promise<string>((f, r) => {
                    bg.default(aProject('IApplicationState', './stateTodos.ts', (filename: string, b: Buffer) => {
                        if (filename.indexOf('stateTodos') !== -1)
                            f(b.toString('utf8'));
                    }, null, '0.5.3'), tsa.create(logger), logger).run();
                })
            };
        });
                
        it('adds note', (done) => {
            testCase
                .do()
                .then(text => {
                    expect(text).toContain(`// 
// This source code was auto-generated by bobflux-gen, Version=0.5.3.
// Don't modify this file but re-generate it by bobflux-gen.
// Bobflux-gen - https://www.npmjs.com/package/bobflux-gen
//`);
                    done();
                });
        });
    });

    describe('buildToStore', () => {
        describe('without parent state key', () => {
            beforeEach(() => {
                testCase = {
                    do: () => new Promise<string>((f, r) => {
                        bg.default(aProject('IApplicationState', './stateTodos.ts', (filename: string, b: Buffer) => {
                            if (filename.indexOf('stateTodos') !== -1)
                                f(b.toString('utf8'));
                        }), tsa.create(logger), logger).run();
                    })
                };
            });

            it('generates builder for direct store saving', (done) => {
                testCase
                    .do()
                    .then(text => {
                        expect(text).toContain(`
    public buildToStore(): s.ITodosState {
        f.bootstrap({ todoSection: this.state });
        return this.state;
    }
`);
                        done();
                    });
            });
        });

        describe('with parent state key', () => {
            beforeEach(() => {
                testCase = {
                    do: () => new Promise<string>((f, r) => {
                        bg.default(aProject('IApplicationState', './stateTodos.ts', (filename: string, b: Buffer) => {
                            if (filename.indexOf('stateTodos') !== -1)
                                f(b.toString('utf8'));
                        }), tsa.create(logger), logger, 'some.root.state.key').run();
                    })
                };
            });

            it('generates builder for direct store saving', (done) => {
                testCase
                    .do()
                    .then(text => {
                        expect(text).toContain(`
    public buildToStore(): s.ITodosState {
        f.bootstrap({ some: { root: { state: { key: { todoSection: this.state } } } } });
        return this.state;
    }
`);
                        done();
                    });
            });
        });
    });

    describe('is Builder helper', () => {
        describe('file stateWithInner', () => {
            beforeEach(() => {
                testCase = {
                    do: () => new Promise<string>((f, r) => {
                        bg.default(aProject('IApplicationState', './stateWithInner.ts', (filename: string, b: Buffer) => {
                            if (filename.indexOf('/tests/stateWithInner.builders.ts') !== -1)
                                f(b.toString('utf8'));
                        }, '../../tests/'), tsa.create(logger), logger).runRecurse();
                    })
                };
            })

            it('generates is builder helper', (done) => {
                testCase
                    .do()
                    .then(text => {
                        expect(text).toContain(`
export function isApplicationStateBuilder(obj: ss.IApplicationState | ApplicationStateBuilder): obj is ApplicationStateBuilder {
    return 'build' in obj;
}
`);
                        done();
                    });
            });
        })
    })

    describe('relative path', () => {
        describe('file stateWithInner', () => {
            beforeEach(() => {
                testCase = {
                    do: () => new Promise<string>((f, r) => {
                        bg.default(aProject('IApplicationState', './stateWithInner.ts', (filename: string, b: Buffer) => {
                            if (filename.indexOf('/tests/stateWithInner.builders.ts') !== -1)
                                f(b.toString('utf8'));
                        }, '../../tests/'), tsa.create(logger), logger).runRecurse();
                    })
                };
            })

            it('imports state file', (done) => {
                testCase
                    .do()
                    .then(text => {
                        expect(text).toContain(`import * as ss from '../spec/resources/stateWithInner';`);
                        done();
                    });
            });

            it('imports external files', (done) => {
                testCase
                    .do()
                    .then(text => {
                        expect(text).toContain(`import * as f from '../spec/flux';`);
                        done();
                    });
            });
        })

        describe('file inner/stateInner', () => {
            beforeEach(() => {
                testCase = {
                    do: () => new Promise<string>((f, r) => {
                        bg.default(aProject('IApplicationState', './stateWithInner.ts', (filename: string, b: Buffer) => {
                            if (filename.indexOf('/tests/inner/stateInner.builders.ts') !== -1)
                                f(b.toString('utf8'));
                        }, '../../tests'), tsa.create(logger), logger).runRecurse();
                    })
                };
            })

            it('imports state file', (done) => {
                testCase
                    .do()
                    .then(text => {
                        expect(text).toContain(`import * as s from '../../spec/resources/inner/stateInner';`);
                        done();
                    });
            });

            it('imports external files', (done) => {
                testCase
                    .do()
                    .then(text => {
                        expect(text).toContain(`import * as f from '../../spec/flux';`);
                        done();
                    });
            });

            it('imports nested state', (done) => {
                testCase
                    .do()
                    .then(text => {
                        expect(text).toContain(`import * as sm from '../../spec/resources/inner/some/someState';`);
                        done();
                    });
            });
        })

        describe('file inner/some/someState', () => {
            beforeEach(() => {
                testCase = {
                    do: () => new Promise<string>((f, r) => {
                        bg.default(aProject('IApplicationState', './stateWithInner.ts', (filename: string, b: Buffer) => {
                            if (filename.indexOf('someState.builders.ts') !== -1)
                                f(b.toString('utf8'));
                        }, '../../tests'), tsa.create(logger), logger).runRecurse();
                    })
                };
            })

            it('imports state file', (done) => {
                testCase
                    .do()
                    .then(text => {
                        expect(text).toContain(`import * as s from '../../../spec/resources/inner/some/someState';`);
                        done();
                    });
            });
        })
    })


    describe('stateWithExternalState', () => {
        describe('file stateWithExternalState', () => {
            beforeEach(() => {
                testCase = {
                    do: () => new Promise<string>((f, r) => {
                        bg.default(aProject('IApplicationState', './stateWithExternalState.ts', (filename: string, b: Buffer) => {
                            if (filename.indexOf('stateWithExternalState') !== -1)
                                f(b.toString('utf8'));
                        }), tsa.create(logger), logger).runRecurse();
                    })
                };
            })

            it('imports state file', (done) => {
                testCase
                    .do()
                    .then(text => {
                        expect(text).toContain(`import * as s from './stateWithExternalState';`);
                        done();
                    });
            });

            it('imports external state file', (done) => {
                testCase
                    .do()
                    .then(text => {
                        expect(text).toContain(`import * as ns from './stateWithNestedState';`);
                        done();
                    });
            });

            it('generates builder fields', (done) => {
                testCase
                    .do()
                    .then(text => {
                        expect(text).toContain(`
    public withStringValue(stringValue: string): ApplicationStateBuilder {
        this.state.stringValue = stringValue;
        return this;
    };

    public withNestedComponentState(nestedComponentState: ns.INestedState): ApplicationStateBuilder {
        this.state.nestedComponentState = nestedComponentState;
        return this;
    };
`);
                        done();
                    });
            });
        })

        describe('file stateWithNestedState', () => {
            beforeEach(() => {
                testCase = {
                    do: () => new Promise<string>((f, r) => {
                        bg.default(aProject('IApplicationState', './stateWithExternalState.ts', (filename: string, b: Buffer) => {
                            if (filename.indexOf('stateWithNestedState') !== -1)
                                f(b.toString('utf8'));
                        }), tsa.create(logger), logger).runRecurse();
                    })
                };
            })

            it('imports state file', (done) => {
                testCase
                    .do()
                    .then(text => {
                        expect(text).toContain(`import * as s from './stateWithNestedState';`);
                        done();
                    });
            });
        })
    })

    describe('file stateTodos', () => {
        beforeEach(() => {
            testCase = {
                do: () => new Promise<string>((f, r) => {
                    bg.default(aProject('IApplicationState', './stateTodos.ts', (filename: string, b: Buffer) => {
                        if (filename.indexOf('stateTodos') !== -1)
                            f(b.toString('utf8'));
                    }), tsa.create(logger), logger).run();
                })
            };
        });

        it('imports state file', (done) => {
            testCase
                .do()
                .then(text => {
                    expect(text).toContain(`import * as s from './stateTodos';`);
                    done();
                })
                .catch(e => {
                    console.log(e);
                    done();
                });
        });

        it('generates builder fields for objects', (done) => {
            testCase
                .do()
                .then(text => {
                    expect(text).toContain(`
    public withTodoSection(todoSection: s.ITodosState | TodosStateBuilder): ApplicationStateBuilder {
        this.state.todoSection = isTodosStateBuilder(todoSection) ? todoSection.build() : todoSection;
        return this;
    };
`);
                    done();
                });
        });

        it('generates builder for array fields', (done) => {
            testCase
                .do()
                .then(text => {
                    expect(text).toContain(`
    public withTodos(...todos: (s.ITodo | TodoBuilder)[]): TodosStateBuilder {
        this.state.todos = todos.map(i => isTodoBuilder(i) ? i.build() : i);
        return this;
    };
`);
                    done();
                });
        });

        it('generates builder for base types', (done) => {
            testCase
                .do()
                .then(text => {
                    expect(text).toContain(`
    public withId(id: number): TodoBuilder {
        this.state.id = id;
        return this;
    };
`);
                    done();
                });
        });

        it('generates build function for application state', (done) => {
            testCase
                .do()
                .then(text => {
                    expect(text).toContain(`
    public build(): s.IApplicationState {
        return this.state;
    }`);
                    done();
                });
        });

        it('generates build function for nested states', (done) => {
            testCase
                .do()
                .then(text => {
                    expect(text).toContain(`
    public build(): s.ITodo {
        return this.state;
    }`);
                    done();
                });
        });

        it('generates builder for application', (done) => {
            testCase
                .do()
                .then(text => {
                    expect(text).toContain(`
export class ApplicationStateBuilder {
    protected state: s.IApplicationState = s.createDefaultApplicationState();

    public withTodoSection(todoSection: s.ITodosState | TodosStateBuilder): ApplicationStateBuilder {
        this.state.todoSection = isTodosStateBuilder(todoSection) ? todoSection.build() : todoSection;
        return this;
    };

    public build(): s.IApplicationState {
        return this.state;
    }
    
    public buildToStore(): s.IApplicationState {
        f.bootstrap(this.state);
        return this.state;
    }
}
`);
                    done();
                });
        });
    });

    function aProject(appStateName: string, appFilePath: string, writeFileCallback: (filename: string, b: Buffer) => void, relativePath: string = null, version: string = 'AVersion'): gb.IGenerationProject {
        return {
            version: version,
            dir: __dirname,
            appStateName: appStateName,
            appSourcesDirectory: path.join(__dirname, 'resources'),
            appStateFileName: path.basename(appFilePath),
            tsOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES5, skipDefaultLibCheck: true },
            writeFileCallback: writeFileCallback,
            relativePath: relativePath
        }
    }
});