import * as g from '../src/cursorsGenerator';
import * as gb from '../src/generator';
import * as tsa from '../src/tsAnalyzer';
import * as log from '../src/logger';
import * as ts from 'typescript';
import * as fs from "fs";
import * as pathPlatformDependent from 'path';
const path = pathPlatformDependent.posix;

describe('cursorsGenerator', () => {
    let testCase: { do: () => Promise<string> };
    let logger = log.create(false, false, false, false);
    
    describe('auto-generated header', () => {
        beforeEach(() => {
            testCase = {
                do: () => new Promise<string>((f, r) => {
                    g.default(aProject('IApplicationState', './stateTodos.ts', (filename: string, b: Buffer) => {
                        if (filename.indexOf('stateTodos') !== -1)
                            f(b.toString('utf8'));
                    }, '0.5.3'), tsa.create(logger), logger).run();
                })
            };
        });

        it('adds note', (done) => {
            testCase
                .do()
                .then(text => {
                    expect(text).toContain(`// 
// This source code was auto-generated by bobflux-gen, Version=0.5.3.
// Don't modify this file but re-generate it by bobflux-gen.
// Bobflux-gen - https://www.npmjs.com/package/bobflux-gen
//`);
                    done();
                });
        });
    });
    
    describe('custom types', () => {
        beforeEach(() => {
            testCase = {
                do: () => new Promise<string>((f, r) => {
                    g.default(aProject('IApplicationState', './stateWithType.ts', (filename: string, b: Buffer) => {
                        if (filename.indexOf('stateWithType') !== -1)
                            f(b.toString('utf8'));
                    }), tsa.create(logger), logger).run();
                })
            };
        });

        it('generates cursor for field of declared type', (done) => {
            testCase
                .do()
                .then(text => {
                    expect(text).toContain(`
export const someMapCursor: bf.ICursor<s.MyMap> = {
    key: 'someMap'
};
`);
                    done();
                });
        });
    });    
    
    describe('enums', () => {
        beforeEach(() => {
            testCase = {
                do: () => new Promise<string>((f, r) => {
                    g.default(aProject('IApplicationState', './stateWithEnum.ts', (filename: string, b: Buffer) => {
                        if (filename.indexOf('stateWithEnum') !== -1)
                            f(b.toString('utf8'));
                    }), tsa.create(logger), logger).run();
                })
            };
        });

        it('generates cursor for field of enum type', (done) => {
            testCase
                .do()
                .then(text => {
                    expect(text).toContain(`
export const someEnumCursor: bf.ICursor<s.SomeEnum> = {
    key: 'someEnum'
};
`);
                    done();
                });
        });
    });

    describe('state todos', () => {
        beforeEach(() => {
            testCase = {
                do: () => new Promise<string>((f, r) => {
                    g.default(aProject('IApplicationState', './stateTodos.ts', (filename: string, b: Buffer) => {
                        if (filename.indexOf('stateTodos') !== -1)
                            f(b.toString('utf8'));
                    }), tsa.create(logger), logger).run();
                })
            };
        });

        it('generates cursors for todos', (done) => {
            testCase
                .do()
                .then(text => {
                    expect(text).toContain(`import * as s from './stateTodos';
import * as f from './flux';

export const rootKey = f.rootCursor.key;

export const rootCursor: f.ICursor<s.IApplicationState> = f.rootCursor;

export default rootCursor;

export const todoSectionCursor: f.ICursor<s.ITodosState> = {
    key: 'todoSection'
};

export const todoSectionEditedTodoCursor: f.ICursor<s.ITodo> = {
    key: 'todoSection.editedTodo'
};

export const todoSectionTodosCursor: f.ICursor<s.ITodo[]> = {
    key: 'todoSection.todos'
};

export const todoSectionEditedTodoIdCursor: f.ICursor<number> = {
    key: 'todoSection.editedTodo.id'
};

export const todoSectionEditedTodoIsDoneCursor: f.ICursor<boolean> = {
    key: 'todoSection.editedTodo.isDone'
};

export const todoSectionEditedTodoNameCursor: f.ICursor<string> = {
    key: 'todoSection.editedTodo.name'
};
`);
                    done();
                })
                .catch(e => { expect(e).toBeUndefined(); done(); });
        });
    });

    describe('state with map', () => {
        beforeEach(() => {
            testCase = {
                do: () => new Promise<string>((f, r) => {
                    g.default(aProject('IApplicationState', './stateWithMap.ts', (filename: string, b: Buffer) => {
                        if (filename.indexOf('stateWithMap') !== -1)
                            f(b.toString('utf8'));
                    }), tsa.create(logger), logger).run();
                })
            };
        });

        it('generates cursors for appState which has map fields', (done) => {
            testCase
                .do()
                .then(text => {
                    expect(text).toContain(`import * as s from './stateWithMap';
import * as bf from 'bobflux';

export const rootKey = bf.rootCursor.key;

export const rootCursor: bf.ICursor<s.IApplicationState> = bf.rootCursor;

export default rootCursor;

export const stringCountsCursor: bf.ICursor<{ [ s: string] : number }> = {
    key: 'stringCounts'
};
`);
                    done();
                });
        });
    });

    describe('state with array', () => {
        beforeEach(() => {
            testCase = {
                do: () => new Promise<string>((f, r) => {
                    g.default(aProject('IApplicationState', './stateWithArray.ts', (filename: string, b: Buffer) => {
                        if (filename.indexOf('stateWithArray') !== -1)
                            f(b.toString('utf8'));
                    }), tsa.create(logger), logger).run();
                })
            };
        });

        it('generates cursors for appState which has array fields', (done) => {
            testCase
                .do()
                .then(text => {
                    expect(text).toContain(`import * as s from './stateWithArray';
import * as bf from 'bobflux';

export const rootKey = bf.rootCursor.key;

export const rootCursor: bf.ICursor<s.IApplicationState> = bf.rootCursor;

export default rootCursor;

export const stringsCursor: bf.ICursor<string[]> = {
    key: 'strings'
};

export const numbersCursor: bf.ICursor<s.INumber[]> = {
    key: 'numbers'
};
`);
                    done();
                });
        });
    });

    describe('state with external state', () => {
        describe('with rootStateKey', () => {
            describe('file stateWithInner', () => {
                beforeEach(() => {
                    testCase = {
                        do: () => new Promise<string>((f, r) => {
                            g.default(aProject('IApplicationState', './stateWithInner.ts', (filename: string, b: Buffer) => {
                                if (filename.indexOf('stateWithInner') !== -1)
                                    f(b.toString('utf8'));
                            }), tsa.create(logger), logger, 'root.subroot').runRecurse();
                        })
                    };
                });

                it('contains rootKey', (done) => {
                    testCase
                        .do()
                        .then(text => {
                            expect(text).toContain(`
export const rootKey = 'root.subroot';
`);
                            done();
                        });
                });

                it('contains correct import prefix of state fields', (done) => {
                    testCase
                        .do()
                        .then(text => {
                            expect(text).toContain(`
export const rootCursor: f.ICursor<ss.IApplicationState> = {
    key: rootKey
};

export default rootCursor;
`);
                            done();
                        });
                });

                it('contains correct import prefix of external nested state fields', (done) => {
                    testCase
                        .do()
                        .then(text => {
                            expect(text).toContain(`
export const innerCursor: f.ICursor<s.IInnerState> = {
    key: rootKey + '.inner'
};
`);
                            done();
                        });
                });
            })

            describe('file stateWithExternalState', () => {
                beforeEach(() => {
                    testCase = {
                        do: () => new Promise<string>((f, r) => {
                            g.default(aProject('IApplicationState', 'stateWithExternalState.ts', (filename: string, b: Buffer) => {
                                if (filename.indexOf('stateWithExternalState') !== -1)
                                    f(b.toString('utf8'));
                            }), tsa.create(logger), logger, 'root.subroot').run();
                        })
                    };
                });

                it('generates cursors for appState fields', (done) => {
                    testCase
                        .do()
                        .then(text => {
                            expect(text).toContain(`
export const rootKey = 'root.subroot';
`);
                            done();
                        });
                });
            });
        });

        describe('without rootStateKey', () => {
            describe('file stateWithInner', () => {
                beforeEach(() => {
                    testCase = {
                        do: () => new Promise<string>((f, r) => {
                            g.default(aProject('IApplicationState', './stateWithInner.ts', (filename: string, b: Buffer) => {
                                if (filename.indexOf('stateWithInner') !== -1)
                                    f(b.toString('utf8'));
                            }), tsa.create(logger), logger).runRecurse();
                        })
                    };
                });

                it('contains import of state file', (done) => {
                    testCase
                        .do()
                        .then(text => {
                            expect(text).toContain(`import * as ss from './stateWithInner';`);
                            done();
                        });
                });

                it('contains import of external nested state file', (done) => {
                    testCase
                        .do()
                        .then(text => {
                            expect(text).toContain(`import * as s from './inner/stateInner';`);
                            done();
                        });
                });

                it('contains correct import prefix of state fields', (done) => {
                    testCase
                        .do()
                        .then(text => {
                            expect(text).toContain(`
export const rootCursor: f.ICursor<ss.IApplicationState> = f.rootCursor;
`);
                            done();
                        });
                });

                it('contains correct import prefix of external nested state fields', (done) => {
                    testCase
                        .do()
                        .then(text => {
                            expect(text).toContain(`
export const innerCursor: f.ICursor<s.IInnerState> = {
    key: 'inner'
};
`);
                            done();
                        });
                });
            })

            describe('file stateWithExternalState', () => {
                beforeEach(() => {
                    testCase = {
                        do: () => new Promise<string>((f, r) => {
                            g.default(aProject('IApplicationState', 'stateWithExternalState.ts', (filename: string, b: Buffer) => {
                                if (filename.indexOf('stateWithExternalState') !== -1)
                                    f(b.toString('utf8'));
                            }), tsa.create(logger), logger).runRecurse();
                        })
                    };
                });

                it('imports related state', (done) => {
                    testCase
                        .do()
                        .then(text => {
                            expect(text.split('\n')[6]).toBe(`import * as s from './stateWithExternalState';`);
                            done();
                        })
                        .catch(e => { expect(e).toBeUndefined(); done(); });
                });

                it('imports bobflux as node module', (done) => {
                    testCase
                        .do()
                        .then(text => {
                            expect(text.split('\n')[7]).toBe(`import * as bf from 'bobflux';`);
                            done();
                        });
                });

                it('imports external state', (done) => {
                    testCase
                        .do()
                        .then(text => {
                            expect(text.split('\n')[8]).toBe(`import * as ns from './stateWithNestedState';`);
                            done();
                        });
                });

                it('generates rootCursor', (done) => {
                    testCase
                        .do()
                        .then(text => {
                            expect(text.split('\n')[10]).toBe(`export const rootKey = bf.rootCursor.key;`);
                            done();
                        });
                });

                it('generates cursors for appState fields from stateWithExternalState', (done) => {
                    testCase
                        .do()
                        .then(text => {
                            expect(text).toContain(`export const stringValueCursor: bf.ICursor<string> = {
    key: 'stringValue'
};

export const nestedComponentStateCursor: bf.ICursor<ns.INestedState> = {
    key: 'nestedComponentState'
};
`);
                            done();
                        });
                });
                
                it('generates cursors for appState fields from stateWithNestedState', (done) => {
                    testCase
                        .do()
                        .then(text => {
                            expect(text).toContain(`
export const nestedComponentStateNumberValueCursor: bf.ICursor<number> = {
    key: 'nestedComponentState.numberValue'
};
`);
                            done();
                        });
                });
            });
        });
    })

    describe('stateWithNestedState', () => {
        beforeEach(() => {
            testCase = {
                do: () => new Promise<string>((f, r) => {
                    g.default(aProject('IApplicationState', './stateWithNestedState.ts', (filename: string, b: Buffer) => {
                        f(b.toString('utf8'));
                    }), tsa.create(logger), logger).run();
                })
            };
        });

        it('imports bobflux as node module', (done) => {
            testCase
                .do()
                .then(text => {
                    expect(text.split('\n')[7]).toBe(`import * as bf from 'bobflux';`);
                    done();
                });
        });

        it('imports related state', (done) => {
            testCase
                .do()
                .then(text => {
                    expect(text.split('\n')[6]).toBe(`import * as s from './stateWithNestedState';`);
                    done();
                });
        });

        it('generates main rootCursor and typed it', (done) => {
            testCase
                .do()
                .then(text => {
                    expect(text.split('\n')[11]).toBe(`export const rootCursor: bf.ICursor<s.IApplicationState> = bf.rootCursor;`);
                    done();
                });
        });

        it('generates cursor for string fields in app state', (done) => {
            testCase
                .do()
                .then(text => {
                    expect(text).toContain(`
export const stringValueCursor: bf.ICursor<string> = {
    key: 'stringValue'
};
`);
                    done();
                });
        });

        it('generates cursor for nested state in app state', (done) => {
            testCase
                .do()
                .then(text => {
                    expect(text).toContain(`
export const stringValueCursor: bf.ICursor<string> = {
    key: 'stringValue'
};
`);
                    done();
                });
        });

        it('generates cursor for secondNested field with parent cursor prefix', (done) => {
            testCase
                .do()
                .then(text => {
                    expect(text).toContain(`
export const secondNestedStringValueCursor: bf.ICursor<string> = {
    key: 'secondNested.stringValue'
};
`);
                    done();
                });
        });

        it('generates cursors for appState fields', (done) => {
            testCase
                .do()
                .then(text => {
                    expect(text).toContain(`import * as s from './stateWithNestedState';
import * as bf from 'bobflux';

export const rootKey = bf.rootCursor.key;

export const rootCursor: bf.ICursor<s.IApplicationState> = bf.rootCursor;

export default rootCursor;

export const stringValueCursor: bf.ICursor<string> = {
    key: 'stringValue'
};

export const nestedCursor: bf.ICursor<s.INestedState> = {
    key: 'nested'
};

export const secondNestedCursor: bf.ICursor<s.ISecondNestedState> = {
    key: 'secondNested'
};

export const nestedNumberValueCursor: bf.ICursor<number> = {
    key: 'nested.numberValue'
};

export const secondNestedStringValueCursor: bf.ICursor<string> = {
    key: 'secondNested.stringValue'
};
`);
                    done();
                });
        });
    });

    describe('state with base types', () => {
        beforeEach(() => {
            testCase = {
                do: () => new Promise<string>((f, r) => {
                    g.default(aProject('IApplicationState', './stateWithBaseTypes.ts', (filename: string, b: Buffer) => {
                        if (filename.indexOf('stateWithBaseTypes') !== -1)
                            f(b.toString('utf8'));
                    }), tsa.create(logger), logger).run();
                })
            };
        });

        it('imports bobflux as node module', (done) => {
            testCase
                .do()
                .then(text => {
                    expect(text.split('\n')[7]).toBe(`import * as bf from 'bobflux';`);
                    done();
                });
        });

        it('imports related state', (done) => {
            testCase
                .do()
                .then(text => {
                    expect(text.split('\n')[6]).toBe(`import * as s from './stateWithBaseTypes';`);
                    done();
                });
        });

        it('generates main rootCursor and typed it', (done) => {
            testCase
                .do()
                .then(text => {
                    expect(text.split('\n')[11]).toBe(`export const rootCursor: bf.ICursor<s.IApplicationState> = bf.rootCursor;`);
                    done();
                });
        });

        it('generates state with base types', (done) => {
            testCase
                .do()
                .then(text => {
                    expect(text).toContain(`import * as s from './stateWithBaseTypes';
import * as bf from 'bobflux';

export const rootKey = bf.rootCursor.key;

export const rootCursor: bf.ICursor<s.IApplicationState> = bf.rootCursor;

export default rootCursor;

export const stringValueCursor: bf.ICursor<string> = {
    key: 'stringValue'
};

export const numberValueCursor: bf.ICursor<number> = {
    key: 'numberValue'
};
`);
                    done();
                });

        });
    });

    it('generates state with parent cursor key', (done) => {
        testCase = {
            do: () => new Promise<string>((f, r) => {
                g.default(aProject('IApplicationState', './stateWithBaseTypes.ts', (filename: string, b: Buffer) => {
                    if (filename.indexOf('stateWithBaseTypes') !== -1)
                        f(b.toString('utf8'));
                }), tsa.create(logger), logger, 'parentCursorKey').run();
            })
        };
        testCase
            .do()
            .then(text => {
                expect(text).toContain(`import * as s from './stateWithBaseTypes';
import * as bf from 'bobflux';

export const rootKey = 'parentCursorKey';

export const rootCursor: bf.ICursor<s.IApplicationState> = {
    key: rootKey
};

export default rootCursor;

export const stringValueCursor: bf.ICursor<string> = {
    key: rootKey + '.stringValue'
};

export const numberValueCursor: bf.ICursor<number> = {
    key: rootKey + '.numberValue'
};
`);
                done();
            });

    });

    describe('createCursorFilePath', () => {
        it('creates file path for cursors from state file path', () => {
            expect(g.createCursorsFilePath('c:/app/state.ts'))
                .toBe('c:/app/state.cursors.ts');
        });
    })

    function aProject(appStateName: string, appFilePath: string, writeFileCallback: (filename: string, b: Buffer) => void, version: string = 'AVersion'): gb.IGenerationProject {
        return {
            version: version,
            dir: __dirname,
            appStateName: appStateName,
            appSourcesDirectory: path.join(__dirname, 'resources'),
            appStateFileName: path.basename(appFilePath),
            tsOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES5, skipDefaultLibCheck: true },
            writeFileCallback: writeFileCallback
        }
    }

    // logger = {
    //     info: (message: string, params?: any) => { },
    //     warning: (message: string, params?: any) => { },
    //     error: (message: string, params?: any) => { },
    //     debug: (message: string, params?: any) => { (message.indexOf('Visited kind') === 0 || message.indexOf('Source result') === 0) && console.log(`Debug: ${message}`, params); }
    // }

});